[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mlcore"
version = "0.0.0-ci"
description = "Dummy mlcore stub for template CI"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.11"

